import type { Metadata } from "next";
import "#/styles/globals.css";
import { ThemeProvider } from "#/components/contexts/theme-provider";
import { TRPCReactProvider } from "#/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          {/* <div vaul-drawer-wrapper=""> enable for vaul drawer scale background feature: not usefull for now*/}
          <TRPCReactProvider>{children}</TRPCReactProvider>
          {/* </div> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
